### ISSUE TITLE
Testimonials and companies.

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [SaturnFramework/SaturnFramework.github.io#1]
Saturn landing page is targeted at CTOs/management/decision makers. Listing some companies using Saturn and adding some short testimonials from its users would be nice.

**Comment by Krzysztof-Cieslak** [comment]
CC: @forki @rmunn @NinoFloris @forki @baronfel @ChrSteinert @jeremyabbott

**Comment by Krzysztof-Cieslak** [comment]
https://github.com/SaturnFramework/SaturnFramework.github.io/blob/wip/index.html#L198-L348

**Comment by Krzysztof-Cieslak** [comment]
Hey, if any of you would be interested in either putting logo of your company or just writing some super short, one sentence testimonial I'd really appreciate - please let me know

**Comment by Krzysztof-Cieslak** [comment]
If you'd be interested how it looks like:
![untitled](https://user-images.githubusercontent.com/5427083/42635519-8e0b93c2-85e6-11e8-91ea-3b86f8d4039b.png)

**Comment by jeremyabbott** [comment]
@Krzysztof-Cieslak here's my testimonial:

I've found Saturn to be the ideal web application framework. The MVC metaphor makes it perfect for teams looking to adopt F# because it supports patterns with which .NET developers are already familiar. Because it makes use of the `Task` computation expression, it also integrates very well with the rest of the .NET ecosystem. Even in its early stages, the CLI makes stubbing out new features incredibly simple. And, because it's leveraging the Giraffe framework, [you know it's fast](https://twitter.com/i/web/status/1008406784212656130).

**Comment by NinoFloris** [comment]
@Krzysztof-Cieslak Consently/Crowded's testimonial:

For [Consently](consently.co) and [Crowded](crowded.co) Saturn pairs perfectly with the productivity and safety we get from F# and applies those same principles to create a great functional first MVC web framework. All batteries are included and the possibility to use Saturn with any existing ASP.NET core library is a killer feature. F# with Saturn helps us get results like no other combination in the .NET ecosystem.

(If you mind two companies you can just pick which one you like best 😉)

**Comment by baronfel** [comment]
We're not actually using it yet, but I'm pushing that direction. Once we have something out I'd be happy to contribute a testimonial.

**Comment by rmunn** [comment]
Same here. Once I've actually used it in practice I'll be happy to say something about it, but I shouldn't do so yet.
